version: 2.1

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: make test
  publish:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run: make build
      - run: make push

workflows:
  test-workflow:
    jobs:
      - test
      - publish:
          requires:
            - test
